- .github/workflows/cr.yml
* `OpenAI`を使用してコードレビュープロセスの効率を向上させたいと考えています。そのために新しいレビューシステムを導入します。このPRの目的は、OpenAIを活用したコードレビューシステムを実装することです。
* `yaml`ファイルを作成して`OpenAI`をコードレビューに適用しました。これにより、コードレビューの効率が向上することを期待しています。
* なし
* `yaml`ファイルの構成に注目していただければと思います。特に `runs-on`, `steps`, `uses`, `env`, `GITHUB_TOKEN`, `OPENAI_API_KEY` などのフィールドについて詳しく見ていただければと思います。
* このPRは新しいシステムを導入するものなので、実際に`OpenAI`がコードレビューに適用されるかどうかを確認するテストが必要です。
* #3 
* コードレビュープログラムのリンクはこちらです: [ChatGPT-CodeReview](https://github.com/anc95/ChatGPT-CodeReview)
> …
> OpenAIを活用したコードレビューボットの導入

- .github/workflows/auto-assign.yml
*  新規に作成されたIssueやプルリクエストに自動的にレビュアーやアサインを割り当てる機能を実装することで、Issueやプルリクエストの管理をより効率的に行います。
* GitHub Actionsの設定ファイル（auto-assign.yml）を作成し、新規Issueとプルリクエストの作成時に自動でアサインを行う設定を追加しました。
* なし
* `auto-assign.yml`ファイルの設定内容とその動作についてご確認いただきたいです。
* 新規Issueやプルリクエストが作成された際の自動アサインの動作を確認する必要があります。
* 関連Issue: #5 
- なし
* P3 : こんな方法もあるんじゃないかな～などの些細な意見です (Chore)。
---
> 自動割り当て機能のためのGitHub Actions設定の追加

- .github/workflows/auto-reviewer.yml
- .github/workflows/auto_be_reviewer.yml
* 新たに作成されたプルリクエストに自動的にレビュワーを割り当てることで、レビュープロセスの効率化と管理の簡素化を実現したいと考えています。
* 主な変更点は、GitHub Actionsを使用して新たなプルリクエストに対して自動的にレビュワーを割り当てる新機能を導入したことです。
* なし
* `auto-reviewer.yml`設定ファイルの設定について特に見ていただきたいです。
* 新機能の動作を確認するために、新たなプルリクエストを作成し、自動的にレビュワーが割り当てられるかを確認する必要があります。
関連するIssue: #12 
* まだありません。
* P3 : こんな方法もあるんじゃないかな～などの些細な意見です (Chore)。
---
> 自動Reviewer当て機能のためのGitHub Actions設定の追加

- .github/workflows/ci.yml
- .gitignore
- DockerFile
* CIの構築
* ci.ymlファイルの修正
* DockerFileの修正
* .gitmessage.txtを利用してCommit Convention 設定
* なし
* なし
#17
* P3 : …
> CIファイル、DockerFile修正

- .github/workflows/cd.yml
* `cd.yml` ファイルのタイプミスを修正しました。
* ポートマッピング用のcd.ymlファイルのタイプミス`「P」`を`「p」`に変更しました。
* `JWT_ACCESS_EXPIRATION` 環境変数のタイプミスを修正しました。
* `リフレッシュ`に関連する未使用の環境変数を削除しました。
* なし
* なし
* なし
* #18 
* P1 : 必ず反映してください (Request Changes) - …
> cd.yml ファイルのタイプミスを修正

- package-lock.json
- package.json
* ランナーインスタンスでコンテナを実行するときにdependencyがなくてエラー発生
* class-transformer dependencyの追加
* なし
* なし
* なし
* #18 
* P3 : …
> dependency追加

- package.json
- prisma/seed.ts
- src/app.module.ts
- src/common/configs/config.interface.ts
- src/common/configs/config.ts
- src/prisma/prisma.module.ts
- src/prisma/prisma.service.spec.ts
- src/prisma/prisma.service.ts
* 認証の実装のため、仮想のデータの管理するための実装
* prismaのモジュールの追加
* configurationファイルにセキュリティ関連バリュー追加
* prismaインスタンスのテスト
* なし
* prismaインスタンスのテスト
* #29
* P2 : 反映を積極的に検討していただければと思います …
> seeding関連ファイルおよびprismaのインスタンスのテストファイル追加

- .github/workflows/cd.yml
- DockerFile
* インスタンスでコンテナーが実行できない。
* buildの結果のmain.jsファイルのpathの修正
* CDworkflowが動作する時既存のimageを削除するように修正
* なし
* なし
* なし
* #17 
* #18 
* P3 : …
> Dockerfile修正およびCDworkflowの修正

- src/common/guards/owner.guard.ts
- src/modules/material-feedback/material-feedback.controller.spec.ts
- src/modules/material/material.controller.spec.ts
- src/modules/prompt/langchain/langchain.service.ts
- src/modules/prompt/prompt.controller.spec.ts
- src/modules/prompt/prompt.controller.ts
- src/modules/prompt/prompt.repository.ts
- src/modules/prompt/prompt.service.ts
* LLMの回答をストリーミングしてUXを高めたかった。
* ストリーミングしてリスポンスするように修正
* ownerGuardのプロンプトのオーナーを確認するロジックの修正
* プロンプトコントローラーのテストコード修正
* なし
* なし
* #54
* P1 : 必ず反映してください (Request Changes) - …
> ロンプトのリスポンスをストリーミングするように修正

- prisma/migrations/20240326061756_create_set_quiz_table_and_quiz_feedback_table/migration.sql
- prisma/migrations/20240326062151_capitalization/migration.sql
- prisma/migrations/20240326074202_add_deadline_column_in_set_quiz_table/migration.sql
- prisma/schema.prisma
- src/modules/auth/auth.service.ts
- src/modules/material/material.controller.spec.ts
- src/modules/material/material.controller.ts
- src/modules/material/material.repository.ts
- src/modules/material/material.service.ts
- src/modules/prompt/message/message.repository.ts
- src/modules/prompt/prompt.controller.spec.ts
- src/modules/prompt/prompt.controller.ts
- src/modules/prompt/prompt.repository.ts
- src/modules/prompt/prompt.service.ts
*  プロンプトモジュールのコントローラーのハンドラーの修正
* 要らないハンドラー`countByCid`に関するコード削除
* 保存されたメッセージを取得するハンドラーをページネーションするように修正
* データベースから保存されたメッセージを取得するメソッドを`message`レポジトリーでするように修正
* なし
* なし
* #56
* P1 : …
> プロンプトモジュールのコントローラーの修正

- prisma/seed.ts
* モデルの名前の修正とあってprisma seedファイルのモデルの名前の修正
* prisma seedファイルのモデルの修正
* なし
* なし
* なし
* #56
* P2 : 反映を積極的に検討していただければと思います …
>  prisma seedファイルの誤字修正

- src/common/decorators/metadata.decorator.ts
- src/common/decorators/use-owner-guards.decorator.ts
- src/common/decorators/use-role-or-owner-guards.decorator.ts
- src/common/guards/owner.guard.ts
- src/modules/material/entity/material.entity.ts
- src/modules/material/material.service.ts
- src/modules/prompt/prompt.controller.ts
- src/modules/quiz-feedback/quiz-feedback.controller.ts
- src/modules/set-quiz/set-quiz.controller.ts
- src/modules/set-quiz/set-quiz.repository.ts
- src/modules/set-quiz/set-quiz.service.ts
* リソースに接近する時の権限確認機能の修正
* OwnerGuardのリファクタリング
* クイズのセットに関する機能の修正
* マテリアルに関する機能の修正
* なし
* なし
- #64 
* P2 : …
> OwnerGuardのリファクタリング

- prisma/migrations/20240423191530_add_is_saved_column_in_file_feedback_table/migration.sql
- prisma/schema.prisma
- src/common/pipes/feedback-type.pipe.ts
- src/modules/material-feedback/langchain/langchain.service.ts
- src/modules/material-feedback/material-feedback.controller.spec.ts
- src/modules/material-feedback/material-feedback.controller.ts
- src/modules/material-feedback/material-feedback.repository.ts
- src/modules/material-feedback/material-feedback.service.ts
* 教育資料のフィードバック機能の修正
* LLM利用したフィードバックをリクエストする時、参照データと文章全体でどれを使うのかを決めるクエリパラメータとしてtype追加
* 特定資料に関する参照データの有無を確認する機能のエンドポイント追加
* フィードバックを受ける時、資料の言語と同じ言語で回答を受けるようにプロンプト修正
* なし
* 
* P1 : …
> 教育資料に対するフィードバック機能の修正

- src/modules/material-feedback/material-feedback.controller.spec.ts
- src/modules/material-feedback/material-feedback.controller.ts
- src/modules/material-feedback/material-feedback.service.ts
* フィードバックを受けられる制限があり、受信できるフィードバックの数を取得するようにしたかった。
* 受信できるフィードバックの数を取得する機能の実装
* なし
* なし
* なし
* [관리자(管理者) - 자료 피드백 수정(フィードバック機能のリファクタリング)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-266)
* …
> 受信できるフィードバックの数を取得する機能の実装

- src/modules/material-feedback/langchain/feedback.example.ts
* fewshotPromptingに利用する例のフォーマット変更
* 資料フィードバックの例のフォーマット変更
* なし
* なし
* なし
* [관리자(管理者) - 자료 피드백 수정(フィードバック機能のリファクタリング)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-266)
* …
> 資料フィードバックの例のフォーマット変更

- prisma/migrations/20240430102149_add_invite_role/migration.sql
- prisma/migrations/20240502023224_add_columns_in_class_table/migration.sql
- prisma/schema.prisma
* ERDと間違っていたカラムを修正
* prismaORMのモデル修正
* なし
* なし
* なし
* [DB 통합(DB統合)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-282)
* P1 : 必ず反映してください (Request …
> PrismaORMのモデルの修正

- src/modules/set-quiz/set-quiz.repository.ts
- src/modules/set-quiz/set-quiz.service.ts
* クイズを採点の時、リクエストのクイズが設定されているクイズと合うかどうかを確認するロジックの修正
* マテリアルのIDを利用して設定されているクイズのリストを取得する
* なし
* なし
* なし
* P2 : …
> クイズを採点するさいのバグフィクス

- src/modules/set-quiz/set-quiz.controller.spec.ts
- src/modules/set-quiz/set-quiz.controller.ts
- src/modules/set-quiz/set-quiz.repository.ts
- src/modules/set-quiz/set-quiz.service.ts
* クイズセットの機能修正
* クイズセット削除機能追加
* クイズセットを生成の時、全体クイズを確認
* なし
* なし
* 削除機能のテストコード
* P3 : …
> クイズセットの機能修正

- src/modules/class-user/class-user.repository.ts
- src/modules/quiz-feedback/quiz-feedback.service.ts
* クイズ、クイズセットのバグフィクス
* クイズ統計から管理者を除外させる
* クイズ統計でクラスユーザー情報を呼び出すときにユーザーイメージを追加
* ユーザーIDを通じたクイズのフィードバックデータ返却 
* なし
* なし
* なし
* [퀴즈, 퀴즈셋 버그 픽스(クイズ、クイズセットのバグフィクス)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-296)
* …
> クイズ、クイズセットの機能の修正

- src/common/guards/owner.guard.ts
* ユーザー（学生）の立場でフィードバックを要求したときに発生するエラーを解決する
* Prisma.ModelName.QuizFeedback のスイッチ ケースでの不必要なオブジェクトの構造化を削除しました。
* なし
* なし
* 
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[タイトル](リンク)の形で添付してください。
* [퀴즈 피드백 버그 픽스(クイズフィードバック機能のバグフィクス)](https://okura-minori.atlassian.net/jira/core/projects/MIN/board?selectedIssue=MIN-302)
* …
> フィードバックを要求したときに発生するエラーを解決

- src/common/guards/owner.guard.ts
- src/modules/quiz/dto/create-update.dto.ts
* CreateQuizzesDto修正
* ArrayMaxSizeバリデーションをCreateQuizzesDtoに追加、最大5個のクイズを生成できるように
* なし
* 
* 
> このPRが解決しようとしている問題に関連するIssueやドキュメント、Jiraがあればリンクを記載してください。Jiraの場合[タイトル](リンク)の形で添付してください。
* P2 : 反映を積極的に検討していただければと思います …
> クイズ生成機能のデータのバリデーション修正
